[project]
name = "modeling_utils"
version = "0.1.0"
dependencies = [
  "pandas>=2.0.1",
  "numpy>=2.1",
  "scikit-learn>=0.21.2",
  "torch>=2.5.1",
  "pytest>=7.4.0",
  "pydantic>=2.5.0",
  "torchmetrics>=1.1.2",
  "x_transformers>=1.27.20",
  "lightning>=2.0.8",
  "wandb>=0.15.11",
]